// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzF-qMkbHdT0Id-5yACUaDz1aqmugAv-0',
    appId: '1:424707334639:web:c795ec67ab8cd9aaf8561a',
    messagingSenderId: '424707334639',
    projectId: 'connect-social-app-be0f4',
    authDomain: 'connect-social-app-be0f4.firebaseapp.com',
    storageBucket: 'connect-social-app-be0f4.appspot.com',
    measurementId: 'G-TSW6D8C9FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNWA_ExNuWN5WYCpO79z-96cd6IDzMfk4',
    appId: '1:424707334639:android:a9ad5bb537af2f27f8561a',
    messagingSenderId: '424707334639',
    projectId: 'connect-social-app-be0f4',
    storageBucket: 'connect-social-app-be0f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyRgYzLE78_wOWpaIChC-6s46G9csIAcQ',
    appId: '1:424707334639:ios:8f82e4175dce76a4f8561a',
    messagingSenderId: '424707334639',
    projectId: 'connect-social-app-be0f4',
    storageBucket: 'connect-social-app-be0f4.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyRgYzLE78_wOWpaIChC-6s46G9csIAcQ',
    appId: '1:424707334639:ios:8f82e4175dce76a4f8561a',
    messagingSenderId: '424707334639',
    projectId: 'connect-social-app-be0f4',
    storageBucket: 'connect-social-app-be0f4.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzF-qMkbHdT0Id-5yACUaDz1aqmugAv-0',
    appId: '1:424707334639:web:b043fb5f234ab011f8561a',
    messagingSenderId: '424707334639',
    projectId: 'connect-social-app-be0f4',
    authDomain: 'connect-social-app-be0f4.firebaseapp.com',
    storageBucket: 'connect-social-app-be0f4.appspot.com',
    measurementId: 'G-PJDRE6L7EX',
  );
}
